[general]
library_names = { "arv.h" = "libaravis" }
library_name = "libaravis"
output_file_path = "../src/LibAravis.jl"
module_name = "LibAravis"
jll_pkg_name = "Aravis_jll"
prologue_file_path = "./prologue.jl"
export_symbol_prefixes = ["arv_", "ARV_"]
use_julia_native_enum_type = false
auto_mutability = false
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
use_deterministic_symbol = true
smart_de_anonymize = true

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = false

[codegen.macro]
macro_mode = "basic"
